CREATE DATABASE IF NOT EXISTS HW4;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `HW4`.* TO 'user'@'%';

FLUSH PRIVILEGES;

USE HW4;

CREATE TABLE IF NOT EXISTS articles(
  id INT NOT NULL auto_increment,
  title VARCHAR(255) NOT NULL,
  article_text TEXT NOT NULL,
  PRIMARY KEY (id)
);
