version: '3.9'
services:
#  database:
#    image: mysql:latest
#    ports:
#    command: --init-file /data/application/init.sql
#    volumes:
#        - ./database/init.sql:/data/application/init.sql
#    environment:
#        MYSQL_DATABASE: HW4
#        MYSQL_USER: user
#        MYSQL_PASSWORD: password

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Generated:1:1,Solved:1:1,Unsolved:1:1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    ports:
      - "6379:6379"
